language: node_js
node_js:
  - "14"
branches:
  only:
    - master
    - staging
services:
  - docker
script:
  - docker-compose -f docker-compose.yaml up --build -d
  - "npm run build:test"
  - "npm run start:test"

# env:
#   - DOCKER_COMPOSE_VERSION=1.26.2
# before_install:
#   - sudo rm /usr/local/bin/docker-compose
#   - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-uname -m > docker-compose
#   - chmod +x docker-compose
#   - sudo mv docker-compose /usr/local/bin
#   - docker-compose -f docker-compose.yaml up --build -d
