language: node_js
node_js:
  - "14"
branches:
  only:
    - master
    - staging
services:
  - docker
before_deploy:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
script:
  - docker-compose -f docker-compose.dev.yaml up --build -d
  - "npm run build:test"
  - "npm run start:test"
  - docker-compose -f docker-compose.dev.yaml down
deploy:
  provider: script
  script:
      docker build -f Dockerfile.production -t epoc/epoc:latest .;
      docker tag epoc/epoc:latest registry.heroku.com/$HEROKU_APP/web;
      docker push epoc/epoc:latest;
      docker push registry.heroku.com/$HEROKU_APP/web;
      heroku container:release web --app $HEROKU_APP
  on:
    branch: master
