version: '3.1'

services:
  epoc:
      build: .
      restart: always
      ports:
        - 3001:3001
      environment:
        NODE_ENV : production

  mongo:
    image: mongo:3
    restart: always
    volumes:
        - "dbdata:/data/db"
    ports:
      - 27017:27017

volumes:
    dbdata:
