version: '3.1'

services:
  mongo:
    image: mongo:3
    restart: always
    volumes:
        - "dbdata_dev:/data/db"
    ports:
      - 27017:27017

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: admin

volumes:
    dbdata_dev:

