openapi: '3.0.0'
info:
  version: '1.0'
  title: "EPOC"
  description: Polls is a simple API allowing consumers to view polls and vote in them.
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
servers:
  - url: http://localhost:3000/
    description: Localhost

paths:
  /login:
    x-summary: Questions Collection
    post:
      description: >-
        You may call this endpoint with your user credentials to validate them against our internal db.
      summary: Login
      requestBody:
            $ref: '#/components/requestBodies/LoginRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWT'
        '401':
          description: 'Invalid username/password combination'

components:
  
  schemas:
  
    LoginBody:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password 
      example:
        username: admin
        password: admin
    JWT:
      title: Json Web Token
      type: string
      example: 3fnadn8cwu9leorfbi2o9reebd8wbed832
  
  requestBodies:
  
    LoginRequest:
      description: 'Login Request'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginBody' 
          example:
            username: 'Mario'
            password: 'mariuccio123'  
  
