swagger: '2.0'
info:
  version: '1.0'
  title: "EPOC"
  description: Polls is a simple API allowing consumers to view polls and vote in them.
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: polls.apiblueprint.org
basePath: /
schemes:
- https
consumes:
- application/json
paths:
  /login:
    x-summary: Questions Collection
    post:
      description: >-
        You may call this endpoint with your user credentials to validate them against our internal db.
      summary: Login
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/JWT'
        401:
          description: 'Invalid username/password combination'

definitions:
  LoginRequest:
    title: Login Request
    type: object
    properties:
      username:
        type: string
      password:
        type: string
    required:
      - username
      - password
    example:
      username: admin
      password: admin
  JWT:
    title: Json Web Token
    type: string
    example: 3fnadn8cwu9leorfbi2o9reebd8wbed832
